//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordenada
    {
        public int IdCoordenadas { get; set; }
        public string Estante { get; set; }
        public string Sala { get; set; }
        public string Librero { get; set; }
        public Nullable<int> Posicion { get; set; }
    }
}
